version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: todouser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD-SHELL", "mysql -u todouser -psecret -h localhost -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:latest
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "mysql://todouser:secret@tcp(db:3306)/todo",
      ]
    command: ["up"]
    volumes:
      - ./infrastructure/db/migrations:/migrations:ro

  seed-runner:
    build:
      context: .
      target: build-stage
    depends_on:
      db:
        condition: service_healthy
    command: go run cmd/seed/main.go
    environment:
      DB_HOST: db
      DB_USER: todouser
      DB_PASSWORD: secret
      DB_NAME: todo
      DB_PORT: 3306

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: todouser
      DB_PASSWORD: secret
      DB_NAME: todo
      DB_PORT: 3306
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
